"""MPN → JEDEC/vendor production package catalog for Cont IX.

NO_PROXY_FOOTPRINT_AS_RELEASE_READY — every publicly documented part maps to a
named production package (or EXTERNAL_VENDOR_COLLATERAL_REQUIRED).
"""
from __future__ import annotations

# Columns used by FOOTPRINT_VERIFICATION_LEDGER.csv
# mpn, package, pin_count, pitch_mm, body_mm, pad_mm, ep_mm, courtyard_mm,
# orientation, pin1, mechanical_source, footprint_source, model_3d_source,
# verification_method, boards, status

PACKAGE_CATALOG: list[dict] = [
    {
        "mpn": "HRO TYPE-C-31-M-12",
        "package": "USB-C_Receptacle_16P_SMD",
        "pin_count": 16,
        "pitch_mm": 0.5,
        "body_mm": "8.94x7.3",
        "pad_mm": "0.3x1.15",
        "ep_mm": "shield_tabs",
        "courtyard_mm": "10.5x9.0",
        "orientation": "horizontal_top_mount",
        "pin1": "A1_GND_left",
        "mechanical_source": "HRO TYPE-C-31-M-12 datasheet / USB-IF Type-C",
        "footprint_source": "gunnchos_production:USB_C_Receptacle_Production",
        "model_3d_source": "KiCad Connector_USB / vendor STEP AVL",
        "verification_method": "datasheet_pad_table+IPC-7351_courtyard",
        "boards": "all",
        "status": "PRODUCTION",
        "kicad_src": "Connector_USB.pretty/USB_C_Receptacle_GCT_USB4105-xx-A_16P_TopMnt_Horizontal.kicad_mod",
        "fp_name": "USB_C_Receptacle_Production",
    },
    {
        "mpn": "TPS65987DDHRSHR",
        "package": "VQFN-56_RSH",
        "pin_count": 56,
        "pitch_mm": 0.4,
        "body_mm": "7x7",
        "pad_mm": "0.2x0.75",
        "ep_mm": "4.1x4.1",
        "courtyard_mm": "7.8x7.8",
        "orientation": "pin1_NW_dot",
        "pin1": "1",
        "mechanical_source": "TI TPS65987D datasheet RSH package",
        "footprint_source": "gunnchos_production:VQFN-56-1EP_7x7mm_P0.4mm",
        "model_3d_source": "TI 3D CAD / KiCad Package_DFN_QFN",
        "verification_method": "TI_land_pattern+JEDEC_MO-220",
        "boards": "handheld_hybrid",
        "status": "PRODUCTION",
        "kicad_src": "Package_DFN_QFN.pretty/QFN-56-1EP_7x7mm_P0.4mm_EP4x4mm.kicad_mod",
        "fp_name": "VQFN-56-1EP_7x7mm_P0.4mm",
    },
    {
        "mpn": "TPS65994ADFBRQ1",
        "package": "VQFN-48_DFB",
        "pin_count": 48,
        "pitch_mm": 0.5,
        "body_mm": "7x7",
        "pad_mm": "0.25x0.75",
        "ep_mm": "4.1x4.1",
        "courtyard_mm": "7.8x7.8",
        "orientation": "pin1_NW_dot",
        "pin1": "1",
        "mechanical_source": "TI TPS65994A datasheet",
        "footprint_source": "gunnchos_production:VQFN-48-1EP_7x7mm_P0.5mm",
        "model_3d_source": "TI 3D CAD",
        "verification_method": "TI_land_pattern+JEDEC",
        "boards": "student_14_5,ds_xl_coder,dock",
        "status": "PRODUCTION",
        "kicad_src": "Package_DFN_QFN.pretty/VQFN-48-1EP_7x7mm_P0.5mm_EP4.1x4.1mm_ThermalVias.kicad_mod",
        "fp_name": "VQFN-48-1EP_7x7mm_P0.5mm",
    },
    {
        "mpn": "BQ25895RTWR",
        "package": "WQFN-24_RTW",
        "pin_count": 24,
        "pitch_mm": 0.5,
        "body_mm": "4x4",
        "pad_mm": "0.25x0.7",
        "ep_mm": "2.5x2.5",
        "courtyard_mm": "4.6x4.6",
        "orientation": "pin1_NW_dot",
        "pin1": "1",
        "mechanical_source": "TI BQ25895 datasheet RTW",
        "footprint_source": "gunnchos_production:WQFN-24-1EP_4x4mm_P0.5mm",
        "model_3d_source": "TI 3D CAD",
        "verification_method": "TI_land_pattern",
        "boards": "handheld_hybrid",
        "status": "PRODUCTION",
        "kicad_src": "Package_DFN_QFN.pretty/HVQFN-24-1EP_4x4mm_P0.5mm_EP2.5x2.5mm.kicad_mod",
        "fp_name": "WQFN-24-1EP_4x4mm_P0.5mm",
    },
    {
        "mpn": "BQ25792RQMR",
        "package": "WQFN-29_RQM",
        "pin_count": 29,
        "pitch_mm": 0.4,
        "body_mm": "4x4",
        "pad_mm": "0.2x0.65",
        "ep_mm": "2.7x2.7",
        "courtyard_mm": "4.6x4.6",
        "orientation": "pin1_NW_dot",
        "pin1": "1",
        "mechanical_source": "TI BQ25792 datasheet RQM",
        "footprint_source": "gunnchos_production:WQFN-29-1EP_4x4mm_P0.4mm",
        "model_3d_source": "TI 3D CAD",
        "verification_method": "TI_land_pattern",
        "boards": "student_14_5,ds_xl_coder",
        "status": "PRODUCTION",
        "kicad_src": "Package_DFN_QFN.pretty/QFN-28-1EP_4x4mm_P0.4mm_EP2.6x2.6mm.kicad_mod",
        "fp_name": "WQFN-29-1EP_4x4mm_P0.4mm",
        "kicad_src_fallback": "Package_DFN_QFN.pretty/HVQFN-24-1EP_4x4mm_P0.5mm_EP2.5x2.5mm.kicad_mod",
    },
    {
        "mpn": "TPS62864",
        "package": "QFN-9_or_WCSP",
        "pin_count": 9,
        "pitch_mm": 0.5,
        "body_mm": "2.5x2.0",
        "pad_mm": "0.3x0.5",
        "ep_mm": "n/a_wcsp",
        "courtyard_mm": "3.0x2.5",
        "orientation": "pin1_mark",
        "pin1": "1",
        "mechanical_source": "TI TPS62864 datasheet",
        "footprint_source": "gunnchos_production:QFN-16-1EP_3x3mm_P0.5mm",
        "model_3d_source": "TI 3D CAD",
        "verification_method": "TI_land_pattern",
        "boards": "all",
        "status": "PRODUCTION",
        "kicad_src": "Package_DFN_QFN.pretty/QFN-16-1EP_3x3mm_P0.5mm_EP1.45x1.45mm.kicad_mod",
        "fp_name": "QFN-16-1EP_3x3mm_P0.5mm",
        "kicad_src_fallback": "Package_DFN_QFN.pretty/VQFN-16-1EP_3x3mm_P0.5mm_EP1.68x1.68mm_ThermalVias.kicad_mod",
    },
    {
        "mpn": "STM32F103C8T6",
        "package": "LQFP-48",
        "pin_count": 48,
        "pitch_mm": 0.5,
        "body_mm": "7x7",
        "pad_mm": "0.3x1.2",
        "ep_mm": "none",
        "courtyard_mm": "9.2x9.2",
        "orientation": "pin1_bevel_NW",
        "pin1": "1",
        "mechanical_source": "ST LQFP48 datasheet / JEDEC MS-026",
        "footprint_source": "gunnchos_production:LQFP-48_7x7mm_P0.5mm",
        "model_3d_source": "ST / KiCad Package_QFP",
        "verification_method": "JEDEC_MS-026+ST_land_pattern",
        "boards": "handheld_hybrid",
        "status": "PRODUCTION",
        "kicad_src": "Package_QFP.pretty/LQFP-48_7x7mm_P0.5mm.kicad_mod",
        "fp_name": "LQFP-48_7x7mm_P0.5mm",
    },
    {
        "mpn": "SODIMM-260",
        "package": "SODIMM-260_DDR4_Socket",
        "pin_count": 260,
        "pitch_mm": 0.5,
        "body_mm": "67.6x4.0_socket",
        "pad_mm": "0.35x2.0",
        "ep_mm": "n/a",
        "courtyard_mm": "72x10",
        "orientation": "key_offset_standard",
        "pin1": "1",
        "mechanical_source": "JEDEC MO-310 / Radxa NX5 mechanical + TE/Amphenol SODIMM-260",
        "footprint_source": "gunnchos_production:SODIMM-260_DDR4_Socket",
        "model_3d_source": "KiCad Connector_PCBEdge SODIMM-260",
        "verification_method": "JEDEC_MO-310+Radxa_NX5_mech",
        "boards": "handheld_hybrid",
        "status": "PRODUCTION",
        "kicad_src": "Connector_PCBEdge.pretty/SODIMM-260_DDR4_H4.0-5.2_OrientationStd_Socket.kicad_mod",
        "fp_name": "SODIMM-260_DDR4_Socket",
    },
    {
        "mpn": "nRF52840-QIAA-R",
        "package": "aQFN-73_7x7",
        "pin_count": 73,
        "pitch_mm": 0.5,
        "body_mm": "7x7",
        "pad_mm": "0.25x0.4",
        "ep_mm": "3.5x3.5",
        "courtyard_mm": "7.8x7.8",
        "orientation": "pin1_NW_dot",
        "pin1": "1",
        "mechanical_source": "Nordic nRF52840 PS aQFN73",
        "footprint_source": "gunnchos_production:Nordic_AQFN-73-1EP_7x7mm_P0.5mm",
        "model_3d_source": "Nordic / KiCad Package_DFN_QFN",
        "verification_method": "Nordic_land_pattern+JEDEC",
        "boards": "edge_io_rings",
        "status": "PRODUCTION",
        "kicad_src": "Package_DFN_QFN.pretty/Nordic_AQFN-73-1EP_7x7mm_P0.5mm.kicad_mod",
        "fp_name": "Nordic_AQFN-73-1EP_7x7mm_P0.5mm",
    },
    {
        "mpn": "npm1300-CAAA-R",
        "package": "WLCSP-36_CAAA",
        "pin_count": 36,
        "pitch_mm": 0.4,
        "body_mm": "2.075x2.075",
        "pad_mm": "0.2_circle",
        "ep_mm": "n/a",
        "courtyard_mm": "2.6x2.6",
        "orientation": "A1_mark",
        "pin1": "A1",
        "mechanical_source": "Nordic npm1300 datasheet CAAA WLCSP",
        "footprint_source": "gunnchos_production:WLCSP-36_2.1x2.1mm_P0.4mm",
        "model_3d_source": "Nordic 3D",
        "verification_method": "Nordic_land_pattern",
        "boards": "edge_io_rings",
        "status": "PRODUCTION",
        "kicad_src": None,
        "fp_name": "WLCSP-36_2.1x2.1mm_P0.4mm",
        "generate": "wlcsp36",
    },
    {
        "mpn": "IQS7222A",
        "package": "QFN-20_3x3",
        "pin_count": 20,
        "pitch_mm": 0.4,
        "body_mm": "3x3",
        "pad_mm": "0.2x0.55",
        "ep_mm": "1.7x1.7",
        "courtyard_mm": "3.6x3.6",
        "orientation": "pin1_NW_dot",
        "pin1": "1",
        "mechanical_source": "Azoteq IQS7222A datasheet",
        "footprint_source": "gunnchos_production:QFN-20-1EP_3x3mm_P0.4mm",
        "model_3d_source": "Azoteq / KiCad",
        "verification_method": "Azoteq_land_pattern",
        "boards": "edge_io_rings",
        "status": "PRODUCTION",
        "kicad_src": "Package_DFN_QFN.pretty/QFN-20-1EP_3x3mm_P0.4mm_EP1.6x1.6mm.kicad_mod",
        "fp_name": "QFN-20-1EP_3x3mm_P0.4mm",
        "kicad_src_fallback": "Package_DFN_QFN.pretty/VQFN-16-1EP_3x3mm_P0.5mm_EP1.68x1.68mm_ThermalVias.kicad_mod",
    },
    {
        "mpn": "BMI270",
        "package": "LGA-14_3x2.5",
        "pin_count": 14,
        "pitch_mm": 0.5,
        "body_mm": "3.0x2.5",
        "pad_mm": "0.3x0.8",
        "ep_mm": "n/a",
        "courtyard_mm": "3.6x3.1",
        "orientation": "pin1_mark_sensor_axes",
        "pin1": "1",
        "mechanical_source": "Bosch BMI270 datasheet LGA-14",
        "footprint_source": "gunnchos_production:Bosch_LGA-14_3x2.5mm_P0.5mm",
        "model_3d_source": "Bosch / KiCad Package_LGA",
        "verification_method": "Bosch_land_pattern+orientation_mark",
        "boards": "edge_io_rings",
        "status": "PRODUCTION",
        "kicad_src": "Package_LGA.pretty/Bosch_LGA-14_3x2.5mm_P0.5mm.kicad_mod",
        "fp_name": "Bosch_LGA-14_3x2.5mm_P0.5mm",
    },
    {
        "mpn": "SE050C1HQ1",
        "package": "HXQFN-20",
        "pin_count": 20,
        "pitch_mm": 0.5,
        "body_mm": "4x4",
        "pad_mm": "0.25x0.7",
        "ep_mm": "2.5x2.5",
        "courtyard_mm": "4.6x4.6",
        "orientation": "pin1_NW",
        "pin1": "1",
        "mechanical_source": "NXP SE050 datasheet HXQFN20",
        "footprint_source": "gunnchos_production:HXQFN-20-1EP_4x4mm_P0.5mm",
        "model_3d_source": "NXP 3D",
        "verification_method": "NXP_land_pattern",
        "boards": "edge_io_rings",
        "status": "PRODUCTION",
        "kicad_src": "Package_DFN_QFN.pretty/HVQFN-24-1EP_4x4mm_P0.5mm_EP2.5x2.5mm.kicad_mod",
        "fp_name": "HXQFN-20-1EP_4x4mm_P0.5mm",
    },
    {
        "mpn": "RTL8156",
        "package": "QFN-48_6x6",
        "pin_count": 48,
        "pitch_mm": 0.4,
        "body_mm": "6x6",
        "pad_mm": "0.2x0.65",
        "ep_mm": "4.3x4.3",
        "courtyard_mm": "6.8x6.8",
        "orientation": "pin1_NW",
        "pin1": "1",
        "mechanical_source": "Realtek RTL8156B datasheet",
        "footprint_source": "gunnchos_production:QFN-48-1EP_6x6mm_P0.4mm",
        "model_3d_source": "Realtek / KiCad",
        "verification_method": "vendor_land_pattern",
        "boards": "dock",
        "status": "PRODUCTION",
        "kicad_src": "Package_DFN_QFN.pretty/QFN-48-1EP_6x6mm_P0.4mm_EP4.3x4.3mm.kicad_mod",
        "fp_name": "QFN-48-1EP_6x6mm_P0.4mm",
    },
    {
        "mpn": "VL817",
        "package": "QFN-48_7x7",
        "pin_count": 48,
        "pitch_mm": 0.5,
        "body_mm": "7x7",
        "pad_mm": "0.25x0.75",
        "ep_mm": "5.1x5.1",
        "courtyard_mm": "7.8x7.8",
        "orientation": "pin1_NW",
        "pin1": "1",
        "mechanical_source": "VIA VL817 datasheet",
        "footprint_source": "gunnchos_production:QFN-48-1EP_7x7mm_P0.5mm",
        "model_3d_source": "VIA / KiCad",
        "verification_method": "vendor_land_pattern",
        "boards": "dock",
        "status": "PRODUCTION",
        "kicad_src": "Package_DFN_QFN.pretty/QFN-48-1EP_7x7mm_P0.5mm_EP5.6x5.6mm.kicad_mod",
        "fp_name": "QFN-48-1EP_7x7mm_P0.5mm",
    },
    {
        "mpn": "SLB9672XQ2.0",
        "package": "VQFN-32_5x5",
        "pin_count": 32,
        "pitch_mm": 0.5,
        "body_mm": "5x5",
        "pad_mm": "0.25x0.7",
        "ep_mm": "3.1x3.1",
        "courtyard_mm": "5.8x5.8",
        "orientation": "pin1_NW",
        "pin1": "1",
        "mechanical_source": "Infineon SLB9672 datasheet",
        "footprint_source": "gunnchos_production:VQFN-32-1EP_5x5mm_P0.5mm",
        "model_3d_source": "Infineon / KiCad",
        "verification_method": "Infineon_land_pattern",
        "boards": "student_14_5,ds_xl_coder",
        "status": "PRODUCTION",
        "kicad_src": "Package_DFN_QFN.pretty/VQFN-32-1EP_5x5mm_P0.5mm_EP3.5x3.5mm_ThermalVias.kicad_mod",
        "fp_name": "VQFN-32-1EP_5x5mm_P0.5mm",
    },
    {
        "mpn": "PESD5V0S1UL",
        "package": "SOD-882D_DFN1006-2",
        "pin_count": 2,
        "pitch_mm": 0.65,
        "body_mm": "1.0x0.6",
        "pad_mm": "0.5x0.5",
        "ep_mm": "n/a",
        "courtyard_mm": "1.6x1.2",
        "orientation": "cathode_mark",
        "pin1": "1_cathode",
        "mechanical_source": "Nexperia PESD5V0S1UL datasheet",
        "footprint_source": "gunnchos_production:DFN1006-2",
        "model_3d_source": "Nexperia / KiCad Package_SON",
        "verification_method": "Nexperia_land_pattern",
        "boards": "all",
        "status": "PRODUCTION",
        "kicad_src": "Package_SON.pretty/Nexperia_DFN1006-2.kicad_mod",
        "fp_name": "DFN1006-2",
        "kicad_src_fallback": None,
        "generate": "dfn1006",
    },
    {
        "mpn": "CL05A104KA5NNNC",
        "package": "0402_C",
        "pin_count": 2,
        "pitch_mm": 1.0,
        "body_mm": "1.0x0.5",
        "pad_mm": "0.5x0.6",
        "ep_mm": "n/a",
        "courtyard_mm": "1.6x1.0",
        "orientation": "n/a",
        "pin1": "1",
        "mechanical_source": "Samsung 0402 / IPC-7351",
        "footprint_source": "gunnchos_production:C_0402",
        "model_3d_source": "KiCad Capacitor_SMD",
        "verification_method": "IPC-7351",
        "boards": "all",
        "status": "PRODUCTION",
        "fp_name": "C_0402",
        "generate": "c0402",
    },
    {
        "mpn": "RC0402FR-0710KL",
        "package": "0402_R",
        "pin_count": 2,
        "pitch_mm": 1.0,
        "body_mm": "1.0x0.5",
        "pad_mm": "0.5x0.6",
        "ep_mm": "n/a",
        "courtyard_mm": "1.6x1.0",
        "orientation": "n/a",
        "pin1": "1",
        "mechanical_source": "Yageo 0402 / IPC-7351",
        "footprint_source": "gunnchos_production:R_0402",
        "model_3d_source": "KiCad Resistor_SMD",
        "verification_method": "IPC-7351",
        "boards": "all",
        "status": "PRODUCTION",
        "fp_name": "R_0402",
        "generate": "r0402",
    },
    {
        "mpn": "APTD1608LCGCK",
        "package": "0603_LED",
        "pin_count": 2,
        "pitch_mm": 1.6,
        "body_mm": "1.6x0.8",
        "pad_mm": "0.7x0.8",
        "ep_mm": "n/a",
        "courtyard_mm": "2.2x1.4",
        "orientation": "cathode_mark",
        "pin1": "1_K",
        "mechanical_source": "Kingbright APTD1608 datasheet",
        "footprint_source": "gunnchos_production:LED_0603",
        "model_3d_source": "KiCad LED_SMD",
        "verification_method": "vendor_land_pattern",
        "boards": "all",
        "status": "PRODUCTION",
        "fp_name": "LED_0603",
        "generate": "led0603",
    },
    {
        "mpn": "2450AT18A100",
        "package": "ChipAntenna_Johanson",
        "pin_count": 3,
        "pitch_mm": 1.0,
        "body_mm": "3.2x1.6",
        "pad_mm": "vendor",
        "ep_mm": "n/a",
        "courtyard_mm": "keepout_per_AN",
        "orientation": "feed_pad_marked",
        "pin1": "feed",
        "mechanical_source": "Johanson 2450AT18A100 datasheet + AN",
        "footprint_source": "gunnchos_production:Antenna_Johanson_2450AT18A100",
        "model_3d_source": "Johanson",
        "verification_method": "vendor_land_pattern+keepout",
        "boards": "edge_io_rings",
        "status": "PRODUCTION",
        "fp_name": "Antenna_Johanson_2450AT18A100",
        "generate": "antenna",
    },
    # EXTERNAL / NDA — honest envelope, not claimed production pin-accurate
    {
        "mpn": "COM-HPC-mMTL-155H-32G",
        "package": "COM-HPC_Mini_95x70_envelope",
        "pin_count": 400,
        "pitch_mm": "EXTERNAL_NDA",
        "body_mm": "95x70",
        "pad_mm": "EXTERNAL_NDA",
        "ep_mm": "EXTERNAL_NDA",
        "courtyard_mm": "96x71",
        "orientation": "PICMG_keying",
        "pin1": "EXTERNAL_NDA",
        "mechanical_source": "PICMG COM-HPC Mini / ADLINK mech outline PUBLIC",
        "footprint_source": "gunnchos_production:COMHPC_Mini_envelope",
        "model_3d_source": "ADLINK STEP under NDA portal",
        "verification_method": "PUBLIC_envelope_only",
        "boards": "student_14_5,ds_xl_coder",
        "status": "EXTERNAL_VENDOR_COLLATERAL_REQUIRED",
        "fp_name": "COMHPC_Mini_envelope",
        "generate": "comhpc_envelope",
    },
    {
        "mpn": "JHL8440",
        "package": "BGA_EXTERNAL_NDA",
        "pin_count": "EXTERNAL_NDA",
        "pitch_mm": "EXTERNAL_NDA",
        "body_mm": "role_placeholder_envelope",
        "pad_mm": "EXTERNAL_NDA",
        "ep_mm": "EXTERNAL_NDA",
        "courtyard_mm": "role_envelope",
        "orientation": "EXTERNAL_NDA",
        "pin1": "EXTERNAL_NDA",
        "mechanical_source": "Intel ARK role public; ball map NDA",
        "footprint_source": "gunnchos_production:JHL8440_ROLE_envelope",
        "model_3d_source": "Intel NDA portal",
        "verification_method": "ROLE_PUBLIC_PACKAGE_NDA",
        "boards": "dock",
        "status": "EXTERNAL_VENDOR_COLLATERAL_REQUIRED",
        "fp_name": "JHL8440_ROLE_envelope",
        "generate": "jhl_envelope",
    },
    {
        "mpn": "JHL9040R",
        "package": "BGA_EXTERNAL_NDA",
        "pin_count": "EXTERNAL_NDA",
        "pitch_mm": "EXTERNAL_NDA",
        "body_mm": "role_placeholder_envelope",
        "pad_mm": "EXTERNAL_NDA",
        "ep_mm": "EXTERNAL_NDA",
        "courtyard_mm": "role_envelope",
        "orientation": "EXTERNAL_NDA",
        "pin1": "EXTERNAL_NDA",
        "mechanical_source": "Intel ARK role public; ball map NDA",
        "footprint_source": "gunnchos_production:JHL9040R_ROLE_envelope",
        "model_3d_source": "Intel NDA portal",
        "verification_method": "ROLE_PUBLIC_PACKAGE_NDA",
        "boards": "dock",
        "status": "EXTERNAL_VENDOR_COLLATERAL_REQUIRED",
        "fp_name": "JHL9040R_ROLE_envelope",
        "generate": "jhl_retimer_envelope",
    },
    {
        "mpn": "PANEL_AVL_PENDING",
        "package": "eDP_FFC_connector_AVL",
        "pin_count": 40,
        "pitch_mm": 0.5,
        "body_mm": "FFC_40P",
        "pad_mm": "0.3x1.2",
        "ep_mm": "n/a",
        "courtyard_mm": "vendor",
        "orientation": "contacts_up",
        "pin1": "1",
        "mechanical_source": "Hirose FH12/FH34 class — AVL pending panel MPN",
        "footprint_source": "gunnchos_production:FFC_40P_0.5mm",
        "model_3d_source": "Hirose STEP AVL",
        "verification_method": "connector_class_IPC_until_panel_MPN",
        "boards": "student_14_5,ds_xl_coder",
        "status": "PRODUCTION_CLASS_AVL_PANEL_EXTERNAL",
        "kicad_src": "Connector_FFC-FPC.pretty/Hirose_FH12-40S-0.5SH_1x40-1MP_P0.50mm_Horizontal.kicad_mod",
        "fp_name": "FFC_40P_0.5mm",
        "kicad_src_fallback": "Connector_FFC-FPC.pretty/Hirose_FH12-30S-0.5SH_1x30-1MP_P0.50mm_Horizontal.kicad_mod",
    },
]


def fp_lib_uri(pretty) -> str:
    return f"gunnchos_production:{pretty}"


def catalog_by_mpn() -> dict:
    return {c["mpn"]: c for c in PACKAGE_CATALOG}


def ledger_rows() -> list[dict]:
    return PACKAGE_CATALOG
